[[xsum]]
arch = "aarch64"
git-tree-sha1 = "1bd7d06f779ca0f0bd730ae73a063050918bc8ed"
os = "macos"

    [[xsum.download]]
    sha256 = "8a8373692c03529b4d4d9dde32bd53ea1fac87c460f24c6d0ca136ec5cd43451"
    url = "https://github.com/JuliaBinaryWrappers/xsum_jll.jl/releases/download/xsum-v3.0.0+0/xsum.v3.0.0.aarch64-apple-darwin.tar.gz"
[[xsum]]
arch = "aarch64"
git-tree-sha1 = "cfb48f2fd88f01b272bab4fa8736a12c87932fcd"
libc = "glibc"
os = "linux"

    [[xsum.download]]
    sha256 = "74d44647fc68b3b41b2615a035883a3fc63bb94632105dcd3c08994708761372"
    url = "https://github.com/JuliaBinaryWrappers/xsum_jll.jl/releases/download/xsum-v3.0.0+0/xsum.v3.0.0.aarch64-linux-gnu.tar.gz"
[[xsum]]
arch = "aarch64"
git-tree-sha1 = "0c97d6b04394b4908ca59a8ec33f0e54a7ddc54d"
libc = "musl"
os = "linux"

    [[xsum.download]]
    sha256 = "5f8078864c17c408757f55403e381d9e5fdfa448cf3a1b2d5e054ff77e0ceba8"
    url = "https://github.com/JuliaBinaryWrappers/xsum_jll.jl/releases/download/xsum-v3.0.0+0/xsum.v3.0.0.aarch64-linux-musl.tar.gz"
[[xsum]]
arch = "aarch64"
git-tree-sha1 = "1d40493cc14c9d2d8a44c9a95b55c6307750b086"
os = "freebsd"

    [[xsum.download]]
    sha256 = "96734c227526cfc08036730d706e1e06624f9a151abc0dfbd8119f08f1f773db"
    url = "https://github.com/JuliaBinaryWrappers/xsum_jll.jl/releases/download/xsum-v3.0.0+0/xsum.v3.0.0.aarch64-unknown-freebsd.tar.gz"
[[xsum]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "81999e1a6ebb2b34f6a2f3b5b986af46b5a227e9"
libc = "glibc"
os = "linux"

    [[xsum.download]]
    sha256 = "58de855d0c5c3add5844669578f20ddd21afa01c80b2acec861490717ba3b53f"
    url = "https://github.com/JuliaBinaryWrappers/xsum_jll.jl/releases/download/xsum-v3.0.0+0/xsum.v3.0.0.armv6l-linux-gnueabihf.tar.gz"
[[xsum]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d638e1cb344fe727859881140f3bce27f3ca7738"
libc = "musl"
os = "linux"

    [[xsum.download]]
    sha256 = "ce956cabd1423d350574bbfd4982d2d5b847845ee41d10cdc97cd55c2c1eb570"
    url = "https://github.com/JuliaBinaryWrappers/xsum_jll.jl/releases/download/xsum-v3.0.0+0/xsum.v3.0.0.armv6l-linux-musleabihf.tar.gz"
[[xsum]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d1a8c75ed0715ff47100ef5bd1341338ab1e8664"
libc = "glibc"
os = "linux"

    [[xsum.download]]
    sha256 = "26857150a9b6d832ad52ef5de92d147abf5c53fe4b62d8d23e898b8bde5fe4f4"
    url = "https://github.com/JuliaBinaryWrappers/xsum_jll.jl/releases/download/xsum-v3.0.0+0/xsum.v3.0.0.armv7l-linux-gnueabihf.tar.gz"
[[xsum]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e84563489ee0591796664b74b509143e36f68f17"
libc = "musl"
os = "linux"

    [[xsum.download]]
    sha256 = "8c46f639abc7c3418347d2760243a4928daecda55d4ca6c3400965ad8fb802f1"
    url = "https://github.com/JuliaBinaryWrappers/xsum_jll.jl/releases/download/xsum-v3.0.0+0/xsum.v3.0.0.armv7l-linux-musleabihf.tar.gz"
[[xsum]]
arch = "i686"
git-tree-sha1 = "78c95f2b22fdd58e4fdfcba66b5438b25cae2de1"
libc = "glibc"
os = "linux"

    [[xsum.download]]
    sha256 = "724678a106057b7f63e03d4893bcdc9838589e8e6df7ee5d4713c682ea875103"
    url = "https://github.com/JuliaBinaryWrappers/xsum_jll.jl/releases/download/xsum-v3.0.0+0/xsum.v3.0.0.i686-linux-gnu.tar.gz"
[[xsum]]
arch = "i686"
git-tree-sha1 = "933cfb3c116619ad38cd6f479fdde2664554ce73"
libc = "musl"
os = "linux"

    [[xsum.download]]
    sha256 = "be8d6ab498155785073d188ece0a5486156b0fa19d49ca4f5e2e09b568e1330d"
    url = "https://github.com/JuliaBinaryWrappers/xsum_jll.jl/releases/download/xsum-v3.0.0+0/xsum.v3.0.0.i686-linux-musl.tar.gz"
[[xsum]]
arch = "i686"
git-tree-sha1 = "910b65bba3646e6146c280e2457f424ce54d03ac"
os = "windows"

    [[xsum.download]]
    sha256 = "e3478ffdb66ff94af8ed74087d95f335fa568f9395cce7a595ac30575eb33aa6"
    url = "https://github.com/JuliaBinaryWrappers/xsum_jll.jl/releases/download/xsum-v3.0.0+0/xsum.v3.0.0.i686-w64-mingw32.tar.gz"
[[xsum]]
arch = "powerpc64le"
git-tree-sha1 = "afdc4a1c2a4cc549df13c49cebcf8f5cb31aa94f"
libc = "glibc"
os = "linux"

    [[xsum.download]]
    sha256 = "5cc8ce96ce2cc430f911dd01ed19e5e534e5f83fa2831b86461326f3499a4372"
    url = "https://github.com/JuliaBinaryWrappers/xsum_jll.jl/releases/download/xsum-v3.0.0+0/xsum.v3.0.0.powerpc64le-linux-gnu.tar.gz"
[[xsum]]
arch = "x86_64"
git-tree-sha1 = "c4f63e2d6357123f1161ef95dc8b76c11f1b0430"
os = "macos"

    [[xsum.download]]
    sha256 = "376d90fdb154041825c2a41015b9797c7f6bba7fca322476af93423cfa35e269"
    url = "https://github.com/JuliaBinaryWrappers/xsum_jll.jl/releases/download/xsum-v3.0.0+0/xsum.v3.0.0.x86_64-apple-darwin.tar.gz"
[[xsum]]
arch = "x86_64"
git-tree-sha1 = "4bca36cfa9b339707dd23941fcda147a5f432a70"
libc = "glibc"
os = "linux"

    [[xsum.download]]
    sha256 = "299f4fe96604e12c1fd83d1f8d9dbab58e686fcd4f7a9af2867956efba3d56d9"
    url = "https://github.com/JuliaBinaryWrappers/xsum_jll.jl/releases/download/xsum-v3.0.0+0/xsum.v3.0.0.x86_64-linux-gnu.tar.gz"
[[xsum]]
arch = "x86_64"
git-tree-sha1 = "236be8880bace72b1b3e507093b161edd4fabd06"
libc = "musl"
os = "linux"

    [[xsum.download]]
    sha256 = "ab8882a27a2bea90b11adc7b8c0924a8151b9c9fd6a66de70708965d920d13e0"
    url = "https://github.com/JuliaBinaryWrappers/xsum_jll.jl/releases/download/xsum-v3.0.0+0/xsum.v3.0.0.x86_64-linux-musl.tar.gz"
[[xsum]]
arch = "x86_64"
git-tree-sha1 = "908d05d09dc30f410719cc6f05af8425b61bc32d"
os = "freebsd"

    [[xsum.download]]
    sha256 = "f7b7ca353b8517a8a0e21d7aae4278db92d4a475fcdff03e653741a4b7aa91c1"
    url = "https://github.com/JuliaBinaryWrappers/xsum_jll.jl/releases/download/xsum-v3.0.0+0/xsum.v3.0.0.x86_64-unknown-freebsd.tar.gz"
[[xsum]]
arch = "x86_64"
git-tree-sha1 = "fa5c45fb742d309053d9da4cf9645f0f05e27dd9"
os = "windows"

    [[xsum.download]]
    sha256 = "65ab6896947ad1eb0af12554748481b4fbf924eb59e9529f885f256234bafc1e"
    url = "https://github.com/JuliaBinaryWrappers/xsum_jll.jl/releases/download/xsum-v3.0.0+0/xsum.v3.0.0.x86_64-w64-mingw32.tar.gz"
