[[xsum]]
arch = "aarch64"
git-tree-sha1 = "bc0f1bc43a6cdf46a8a4bdc9b2a82e09610cacb6"
os = "macos"

    [[xsum.download]]
    sha256 = "4220c50e4615c3ca0cf5db0cbb4a8bbfb3628229c80575ed1fe91d5b3174e0dc"
    url = "https://github.com/JuliaBinaryWrappers/xsum_jll.jl/releases/download/xsum-v2.0.0+0/xsum.v2.0.0.aarch64-apple-darwin.tar.gz"
[[xsum]]
arch = "aarch64"
git-tree-sha1 = "dc94964953bedadb65e222ee2f3794dafcd87999"
libc = "glibc"
os = "linux"

    [[xsum.download]]
    sha256 = "b22281415893c6c03187a7a078e6b1b4c50d1400944cbb8108005c997083a195"
    url = "https://github.com/JuliaBinaryWrappers/xsum_jll.jl/releases/download/xsum-v2.0.0+0/xsum.v2.0.0.aarch64-linux-gnu.tar.gz"
[[xsum]]
arch = "aarch64"
git-tree-sha1 = "77541228daa917e60808974564923c992591ea74"
libc = "musl"
os = "linux"

    [[xsum.download]]
    sha256 = "677e4d2a5fe123d8194c1d9ede64c0cc0d5f15f524aae85f116b30acd6017552"
    url = "https://github.com/JuliaBinaryWrappers/xsum_jll.jl/releases/download/xsum-v2.0.0+0/xsum.v2.0.0.aarch64-linux-musl.tar.gz"
[[xsum]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ab0c98269f7875424203405f56323472a33541fc"
libc = "glibc"
os = "linux"

    [[xsum.download]]
    sha256 = "81adf719ff8ab15156942bd874115cc606d4b91268c37744d5e11d014ded8bb1"
    url = "https://github.com/JuliaBinaryWrappers/xsum_jll.jl/releases/download/xsum-v2.0.0+0/xsum.v2.0.0.armv6l-linux-gnueabihf.tar.gz"
[[xsum]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "8e94dc200e3339e05cef4a13328d097a10cfdf77"
libc = "musl"
os = "linux"

    [[xsum.download]]
    sha256 = "06a3426049aedd96f04140065f3186bb45d516adce20a1f3747e68b3dc050ee0"
    url = "https://github.com/JuliaBinaryWrappers/xsum_jll.jl/releases/download/xsum-v2.0.0+0/xsum.v2.0.0.armv6l-linux-musleabihf.tar.gz"
[[xsum]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "8a04750543a5d4dc3709f0572e4cf8b0a8d0e643"
libc = "glibc"
os = "linux"

    [[xsum.download]]
    sha256 = "c496dca1566bd76a7ff07b15372a15f019be3df8265c61ea0f9e562c6869beb1"
    url = "https://github.com/JuliaBinaryWrappers/xsum_jll.jl/releases/download/xsum-v2.0.0+0/xsum.v2.0.0.armv7l-linux-gnueabihf.tar.gz"
[[xsum]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "bc3dffcff6fa704bad1c4f5439f8445cac2e4958"
libc = "musl"
os = "linux"

    [[xsum.download]]
    sha256 = "d6a419c71f7587a1f9eafab29f302f5c6472c3f18eabb78a8173f748006a0c7f"
    url = "https://github.com/JuliaBinaryWrappers/xsum_jll.jl/releases/download/xsum-v2.0.0+0/xsum.v2.0.0.armv7l-linux-musleabihf.tar.gz"
[[xsum]]
arch = "i686"
git-tree-sha1 = "6270f13daa2451faab4fff3ddbe88eb2535d8e47"
libc = "glibc"
os = "linux"

    [[xsum.download]]
    sha256 = "fbc47f0b9ecc0500df99bf328fbbd72fa051007fc2d5e763db6bac055e9ff6b6"
    url = "https://github.com/JuliaBinaryWrappers/xsum_jll.jl/releases/download/xsum-v2.0.0+0/xsum.v2.0.0.i686-linux-gnu.tar.gz"
[[xsum]]
arch = "i686"
git-tree-sha1 = "bda972dbabdd50a7e0d831cbe1402c294b7c5485"
libc = "musl"
os = "linux"

    [[xsum.download]]
    sha256 = "2eb0b11a05af74fcb8828843b30b297f12ce850a94629dcc2c07db4831d0fd8c"
    url = "https://github.com/JuliaBinaryWrappers/xsum_jll.jl/releases/download/xsum-v2.0.0+0/xsum.v2.0.0.i686-linux-musl.tar.gz"
[[xsum]]
arch = "i686"
git-tree-sha1 = "18d5493750ba1d5374a48828f0c99fa06e7861f3"
os = "windows"

    [[xsum.download]]
    sha256 = "2948c6f87e58cde76462f105233853ebc18295748785b67a26f08a8ebc44e163"
    url = "https://github.com/JuliaBinaryWrappers/xsum_jll.jl/releases/download/xsum-v2.0.0+0/xsum.v2.0.0.i686-w64-mingw32.tar.gz"
[[xsum]]
arch = "powerpc64le"
git-tree-sha1 = "f58ecb74047b35036f4558d2edab5003f0955572"
libc = "glibc"
os = "linux"

    [[xsum.download]]
    sha256 = "5ebec1def153ee44d5b5bcb08adfef65fc422bcdaca1374ad1ba19cd1420abf7"
    url = "https://github.com/JuliaBinaryWrappers/xsum_jll.jl/releases/download/xsum-v2.0.0+0/xsum.v2.0.0.powerpc64le-linux-gnu.tar.gz"
[[xsum]]
arch = "x86_64"
git-tree-sha1 = "e0e57b04b85e4761f741e302de15cb16c00a12cc"
os = "macos"

    [[xsum.download]]
    sha256 = "fa134706c4fd222067efa1cdb674b0076b6648233b7cb484fa1bade79dbcaf25"
    url = "https://github.com/JuliaBinaryWrappers/xsum_jll.jl/releases/download/xsum-v2.0.0+0/xsum.v2.0.0.x86_64-apple-darwin.tar.gz"
[[xsum]]
arch = "x86_64"
git-tree-sha1 = "8b887410fc8c1dbe7a01117088adebcdd67df374"
libc = "glibc"
os = "linux"

    [[xsum.download]]
    sha256 = "d25a516442594c7eb526d3101e58a7b4f7926328c23d118a478679bb320a0c3e"
    url = "https://github.com/JuliaBinaryWrappers/xsum_jll.jl/releases/download/xsum-v2.0.0+0/xsum.v2.0.0.x86_64-linux-gnu.tar.gz"
[[xsum]]
arch = "x86_64"
git-tree-sha1 = "6d8aa37dea41528a35e362611314067a3ddd82a7"
libc = "musl"
os = "linux"

    [[xsum.download]]
    sha256 = "324d49800cec6ec5dc5a1998f9072722563e9896840f4c1f4b6be7124969aa82"
    url = "https://github.com/JuliaBinaryWrappers/xsum_jll.jl/releases/download/xsum-v2.0.0+0/xsum.v2.0.0.x86_64-linux-musl.tar.gz"
[[xsum]]
arch = "x86_64"
git-tree-sha1 = "61bb5393fdec77be57548786a9251abebb0e3d90"
os = "freebsd"

    [[xsum.download]]
    sha256 = "69845da54a540b4d8006aaa1c116d219fa4dc95a494c3e1b2903d7fc15414ca0"
    url = "https://github.com/JuliaBinaryWrappers/xsum_jll.jl/releases/download/xsum-v2.0.0+0/xsum.v2.0.0.x86_64-unknown-freebsd.tar.gz"
[[xsum]]
arch = "x86_64"
git-tree-sha1 = "fbea9a189899407a9a3938bd5d2fe4adf13e18c4"
os = "windows"

    [[xsum.download]]
    sha256 = "12b7aac4768d4ac9774f6d3b789e8d3cf8016dee9ca1a9198518dc578d8a8cd2"
    url = "https://github.com/JuliaBinaryWrappers/xsum_jll.jl/releases/download/xsum-v2.0.0+0/xsum.v2.0.0.x86_64-w64-mingw32.tar.gz"
