# Autogenerated wrapper script for xsum_jll for i686-w64-mingw32
export libxsum

JLLWrappers.@generate_wrapper_header("xsum")
JLLWrappers.@declare_library_product(libxsum, "libxsum.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libxsum,
        "bin\\libxsum.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
